
---
title: "2023 Collaborating for Better Health: A Multi-Specialty Conference Handbook"
format: 
  html:
    pandoc:
      from: latex
      to: html
---

\documentclass{article}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{svg}
\usepackage{pdfpages}
\usepackage{tikz}

%Here is an example of a LaTeX script that you can use as a starting point for creating the conference handbook for your Taiwan-Somaliland Medical Conference in August 2023:

%```latex by chatGPT

%% x
%\title{2023 COLLABORATING FOR BETTER HEALTH:
%A MULTI-SPECIALTY CONFERENCE}
%\date{13-14 August 2023}

\begin{document}

%\begin{center} % to remove Fig.
%\end{center}

\begin{titlepage}
%    \centering

%\begin{center}
\hspace*{-0.7cm}%
\begin{tikzpicture} % tikzfigure
%\begin{minipage}[b]{1\linewidth}

\includesvg[height=3.0cm, distort=false]{Flag_of_the_Republic_of_China.svg}
\hspace{1.4cm}
%\includesvg[width=0.17\linewidth]{TMM_logo.svg}
%\hspace{3cm}
\includesvg[height=3.0cm, distort=false]{Flag_of_Somaliland.svg}
%\captionof{Figure}{xx}
%\end{minipage}
\end{tikzpicture}
    \vspace{4cm}
    
\centering
    {\Huge\bfseries % Taiwan---Somaliland \\
    2023 COLLABORATING FOR BETTER HEALTH:
A MULTI-SPECIALTY CONFERENCE\\
    Handbook\par}
    \vspace{1.5cm}
    %\hspace{4cm} 
    {\Large 13-14 August 2023\par}

%\end{center}

\vspace{2.5cm}

\includesvg[height=4.0cm, distort=false]{TMM_logo.svg}


\end{titlepage}


%\maketitle

\clearpage

\section*{Overview}
In August of 2023, Taiwan and Somaliland will host a medical conference. Medical professionals from around the country gather at this conference to exchange ideas and discuss recent advancements. Hemodialysis, live-donor organ transplants, forensics, otolaryngology, oral and maxillofacial surgery, non-communicable illnesses, the Taiwanese experience with HBV/HCV, and the present situation in Somaliland are just a few of the topics that will be discussed during the conference. We anticipate that by disseminating this knowledge to medical professionals in many public hospitals and private sectors in major cities across Somaliland, we may encourage sharing knowledge and best practices amongst them and eventually enhance patient care.


\section*{Conference Schedule}
The conference will take place over two half days in the morning on August 13 and August 14.

\includepdf[page={1}]{TMM_SLN_tikzposter_2023Aug__portrait_agenda___TMM_Conference.pdf}
%\include{agenda_poster}

%\subsection*{August 13}
%\begin{itemize}
%    \item 9:00 AM - Opening remarks
%    \item 9:30 AM - Keynote speaker
%    \item 10:30 AM - Break
%    \item 11:00 AM - Session 1
%    \item 12:00 PM - Lunch
%\end{itemize}

%\subsection*{August 14}
%\begin{itemize}
%    \item 9:00 AM - Session 2
%    \item 10:00 AM - Break
%    \item 10:30 AM - Session 3
%    \item 11:30 AM - Closing remarks
%    \item 12:00 PM - Lunch
%\end{itemize}

\section*{Speaker Biographies}
% Add speaker biographies or CVs here

\section*{Abstracts of Presentations}
% Add abstracts of presentations here

% Tex Chi
\includepdf[pages={1}]{AcademicCV_Li_Hsing_Chi2023.pdf}
\includepdf[pages={1,2}]{HGH_research_proposal_fluorosis_DrMukhtar_DrFadomu.pdf}


\end{document}

