---
title: "2023/06/19 醫療團報告"
format: html
---
1) 婦女公衛篩檢計劃(pap smear)
目的：計劃的目的是由婦科專家醫師，替索蘭1,000名婦女進行子宮頸抺片檢查(pap smear)。因應HGH醫院婦產科主任的建議，目前準備進度，關鍵耗材由萬芳醫院寄送索蘭(06/13抵達，進行清關流程，約須時二週）。HGH婦產科診間已準備完成，病理科亦在擴增檢驗與報告量能，並申請萬芳醫院病理科支援 telepathology閲片、診斷。
如過程順利，便可繼續提供相關耗材協助，增加篩檢量能，由醫院擴展至整個市區。期望未來可以晉身為國家公衛政策之一，以及期待提早檢測出「子宮頸癌前病變」的發生，並減少子宮頸癌症的發生率及死亡率。
婦產科專家 Dr. Dave 林醫師亦將於2023/07/14 任務期滿返臺，***醫團擬製作 certificate 金牌***，恭請大使表揚林醫師的辛勞與功勞。

2) 下一棒專家為萬芳醫院急診部***巫昀祐醫師**將於2023/07/05 到任，已於2023/06/09 與HGH急診部門的主任，線上討論未來的合作方向。

3) 護理師報告：
籌備「基礎護理能力訓練強化計畫」 ，與HGH、UoH、SLNMA（護師協會） 先行辦理「護理師之基礎護理能力」評估問卷，已於5/23-5/25完成HGH全院護理師（500員）每班抽樣調查56人，將據此分析結果後，於七月份開始第一階段計劃。

4) 2023/06/14 ***World Blood Donor Day*** 活動，僅有一週的籌備時間，
2019 是 National Blood Bank Somaliland 成立、當年元月份舉辦第一次捐血活動（總統捐血，HGH Dr Askar 負責篩檢、測量血壓：衛生部長致詞）。
2023 是歷史上的***第二次捐血活動，衛生部長 Dr. Hassan Mohamed Ali 蒞臨致詞***，Dr. Askar 負責解說、宣導捐血教育，醫療團醫師捐血500mL， HGH 兩名醫師亦主動捐血，其中包含一位女醫師（女性捐血者稀少，因為種種因素）。同時在 University of Hargeis 亦開設臨時捐血站，醫學生參與捐血者20名。二地一共收集33袋（每袋500mL血）。
為了增加宣傳與吸引捐血者，同場加映口腔健康篩檢義診，衛生部長與檢驗部主任二名，率先報名參加。會後討論，發現
National Blood Bank 有許多可以改進的空間，例如，血袋儲量的限制，篩檢流程與捐血衛生健育，捐血時的血袋處理流程，以及捐血後的重要提醒。
***Next: World Hepatitis Day (2023/07/28)***

5) ***萬芳醫院訪問索蘭  2023/08/11-16*** (08/13-14 Medical Conference; 08/14-15 ENT campaign for tonsillectomy)，同場將安排捐贈儀式(C-arm X-ray, Arterial Blood gas ABG 血液氣體分析儀, 口腔顎面外科之鈦金屬骨板與器械)。
C-arm x-光機為開刀房骨科手術儀器，ABG將設置在急診(ED)、加護病房(ICU)、兒童加護病房(PICU)、以及洗腎中心(HD)。另有NICU 新生兒加護病房之照護臺，與黃疸光照治療設備（heater with LED phototherapy）。

6) 因應DG Dr. Hergeye 的請求，醫療團一直在進行 HGH 開刀房改進計劃，五月份安裝新式手術臺，骨科手術器械亦倍增五月份手術器械倍增， autoclave 高溫高壓消毒鍋倍增，近日***骨科手術的數量與速度亦倍增***，而中午之前均能提前完成當日安排的全部手術。骨科總住院醫師 Dr Hassan手術加速且有效率，除了醫師技術純熟是關鍵，器械數量足夠，清潔消毒迅速也是重要關鍵之一。

7) Telemedicine 視訊會診，索蘭外交部長（亦為執業的神經生理學醫師）親自轉介的年輕人 Mr. Iid Saleban Dahir (腦瘤患者，雙眼已盲），雙和醫院神經外科鐘醫師已完成會診（2023/05/29），目前等待其治療計畫書與醫療費用評估。06/06 醫療團到宅訪視 Mr. Iid情況穩定，但苦於頭疼與頸部肌肉痠疼，期待能早日接受治療。
預計***2023/07/19於萬芳醫院***，接受全身健康檢查的貴賓，是Mr. Ahmed Abdi Nur (衛生部前任外交委員會主席)，他的兒子目前亦在臺北醫學大學就讀碩士班。夫妻二人均已取得Taiwan VISA。
 
8) NGO AN-NYA 為德國外科醫師的協會，每年定期派遺專家五人小組，到訪索蘭與Nigeria。本週到訪索蘭HGH，為期二週，替骨科部醫師進行基礎外科訓練，以及手術指導。(參考教材為 WHO "Surgical Care at the District Hospital") 
 

